import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'


export default function Home() {
  return (
    <>
      <Head>
        <title>Next by Sean</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.title}>Sean</h1>
      <Link href="/page" className={styles.links}>點我</Link>
      <Link href="/todolist" >TO DO LIST</Link>
    </>
  )
}
